import Foundation
import WeatherAPI

public extension SampleData {

    static var hourlyGridpointForecast: Feature<GridpointForecast> {
        try! decode(fromJSON: hourlyGridpointForecastSource)
    }

    static let hourlyGridpointForecastSource = """
{
    "@context": [
        "https://geojson.org/geojson-ld/geojson-context.jsonld",
        {
            "@version": "1.1",
            "wx": "https://api.weather.gov/ontology#",
            "geo": "http://www.opengis.net/ont/geosparql#",
            "unit": "http://codes.wmo.int/common/unit/",
            "@vocab": "https://api.weather.gov/ontology#"
        }
    ],
    "type": "Feature",
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                [
                    -71.082352599999993,
                    42.374591799999997
                ],
                [
                    -71.08751629999999,
                    42.353187699999999
                ],
                [
                    -71.058549299999996,
                    42.349369799999998
                ],
                [
                    -71.053379699999994,
                    42.3707736
                ],
                [
                    -71.082352599999993,
                    42.374591799999997
                ]
            ]
        ]
    },
    "properties": {
        "updated": "2021-10-25T19:21:26+00:00",
        "units": "us",
        "forecastGenerator": "HourlyForecastGenerator",
        "generatedAt": "2021-10-25T19:35:49+00:00",
        "updateTime": "2021-10-25T19:21:26+00:00",
        "validTimes": "2021-10-25T13:00:00+00:00/P8DT6H",
        "elevation": {
            "unitCode": "wmoUnit:m",
            "value": 3.9624000000000001
        },
        "periods": [
            {
                "number": 1,
                "name": "",
                "startTime": "2021-10-25T15:00:00-04:00",
                "endTime": "2021-10-25T16:00:00-04:00",
                "isDaytime": true,
                "temperature": 56,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/day/rain,30?size=small",
                "shortForecast": "Chance Light Rain",
                "detailedForecast": ""
            },
            {
                "number": 2,
                "name": "",
                "startTime": "2021-10-25T16:00:00-04:00",
                "endTime": "2021-10-25T17:00:00-04:00",
                "isDaytime": true,
                "temperature": 55,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/day/rain,30?size=small",
                "shortForecast": "Chance Light Rain",
                "detailedForecast": ""
            },
            {
                "number": 3,
                "name": "",
                "startTime": "2021-10-25T17:00:00-04:00",
                "endTime": "2021-10-25T18:00:00-04:00",
                "isDaytime": true,
                "temperature": 55,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/day/rain,30?size=small",
                "shortForecast": "Chance Light Rain",
                "detailedForecast": ""
            },
            {
                "number": 4,
                "name": "",
                "startTime": "2021-10-25T18:00:00-04:00",
                "endTime": "2021-10-25T19:00:00-04:00",
                "isDaytime": false,
                "temperature": 54,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "9 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/night/rain,20?size=small",
                "shortForecast": "Patchy Fog",
                "detailedForecast": ""
            },
            {
                "number": 5,
                "name": "",
                "startTime": "2021-10-25T19:00:00-04:00",
                "endTime": "2021-10-25T20:00:00-04:00",
                "isDaytime": false,
                "temperature": 54,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "9 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/night/rain,30?size=small",
                "shortForecast": "Chance Light Rain",
                "detailedForecast": ""
            },
            {
                "number": 6,
                "name": "",
                "startTime": "2021-10-25T20:00:00-04:00",
                "endTime": "2021-10-25T21:00:00-04:00",
                "isDaytime": false,
                "temperature": 54,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "9 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/night/rain,30?size=small",
                "shortForecast": "Chance Light Rain",
                "detailedForecast": ""
            },
            {
                "number": 7,
                "name": "",
                "startTime": "2021-10-25T21:00:00-04:00",
                "endTime": "2021-10-25T22:00:00-04:00",
                "isDaytime": false,
                "temperature": 54,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "9 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/night/rain,40?size=small",
                "shortForecast": "Chance Light Rain",
                "detailedForecast": ""
            },
            {
                "number": 8,
                "name": "",
                "startTime": "2021-10-25T22:00:00-04:00",
                "endTime": "2021-10-25T23:00:00-04:00",
                "isDaytime": false,
                "temperature": 54,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "9 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/night/rain,50?size=small",
                "shortForecast": "Chance Light Rain",
                "detailedForecast": ""
            },
            {
                "number": 9,
                "name": "",
                "startTime": "2021-10-25T23:00:00-04:00",
                "endTime": "2021-10-26T00:00:00-04:00",
                "isDaytime": false,
                "temperature": 54,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "9 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/night/rain,60?size=small",
                "shortForecast": "Light Rain Likely",
                "detailedForecast": ""
            },
            {
                "number": 10,
                "name": "",
                "startTime": "2021-10-26T00:00:00-04:00",
                "endTime": "2021-10-26T01:00:00-04:00",
                "isDaytime": false,
                "temperature": 54,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "9 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/night/rain,70?size=small",
                "shortForecast": "Light Rain Likely",
                "detailedForecast": ""
            },
            {
                "number": 11,
                "name": "",
                "startTime": "2021-10-26T01:00:00-04:00",
                "endTime": "2021-10-26T02:00:00-04:00",
                "isDaytime": false,
                "temperature": 54,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "9 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/night/rain,70?size=small",
                "shortForecast": "Light Rain Likely",
                "detailedForecast": ""
            },
            {
                "number": 12,
                "name": "",
                "startTime": "2021-10-26T02:00:00-04:00",
                "endTime": "2021-10-26T03:00:00-04:00",
                "isDaytime": false,
                "temperature": 54,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/night/rain,80?size=small",
                "shortForecast": "Light Rain",
                "detailedForecast": ""
            },
            {
                "number": 13,
                "name": "",
                "startTime": "2021-10-26T03:00:00-04:00",
                "endTime": "2021-10-26T04:00:00-04:00",
                "isDaytime": false,
                "temperature": 54,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/night/rain,80?size=small",
                "shortForecast": "Light Rain",
                "detailedForecast": ""
            },
            {
                "number": 14,
                "name": "",
                "startTime": "2021-10-26T04:00:00-04:00",
                "endTime": "2021-10-26T05:00:00-04:00",
                "isDaytime": false,
                "temperature": 55,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/night/rain,80?size=small",
                "shortForecast": "Light Rain",
                "detailedForecast": ""
            },
            {
                "number": 15,
                "name": "",
                "startTime": "2021-10-26T05:00:00-04:00",
                "endTime": "2021-10-26T06:00:00-04:00",
                "isDaytime": false,
                "temperature": 55,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/night/rain?size=small",
                "shortForecast": "Light Rain Likely",
                "detailedForecast": ""
            },
            {
                "number": 16,
                "name": "",
                "startTime": "2021-10-26T06:00:00-04:00",
                "endTime": "2021-10-26T07:00:00-04:00",
                "isDaytime": true,
                "temperature": 55,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Light Rain Likely",
                "detailedForecast": ""
            },
            {
                "number": 17,
                "name": "",
                "startTime": "2021-10-26T07:00:00-04:00",
                "endTime": "2021-10-26T08:00:00-04:00",
                "isDaytime": true,
                "temperature": 55,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Light Rain Likely",
                "detailedForecast": ""
            },
            {
                "number": 18,
                "name": "",
                "startTime": "2021-10-26T08:00:00-04:00",
                "endTime": "2021-10-26T09:00:00-04:00",
                "isDaytime": true,
                "temperature": 54,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "12 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Light Rain Likely",
                "detailedForecast": ""
            },
            {
                "number": 19,
                "name": "",
                "startTime": "2021-10-26T09:00:00-04:00",
                "endTime": "2021-10-26T10:00:00-04:00",
                "isDaytime": true,
                "temperature": 56,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "13 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Light Rain Likely",
                "detailedForecast": ""
            },
            {
                "number": 20,
                "name": "",
                "startTime": "2021-10-26T10:00:00-04:00",
                "endTime": "2021-10-26T11:00:00-04:00",
                "isDaytime": true,
                "temperature": 58,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "13 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Light Rain Likely",
                "detailedForecast": ""
            },
            {
                "number": 21,
                "name": "",
                "startTime": "2021-10-26T11:00:00-04:00",
                "endTime": "2021-10-26T12:00:00-04:00",
                "isDaytime": true,
                "temperature": 58,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Light Rain Likely",
                "detailedForecast": ""
            },
            {
                "number": 22,
                "name": "",
                "startTime": "2021-10-26T12:00:00-04:00",
                "endTime": "2021-10-26T13:00:00-04:00",
                "isDaytime": true,
                "temperature": 58,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "16 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Light Rain Likely",
                "detailedForecast": ""
            },
            {
                "number": 23,
                "name": "",
                "startTime": "2021-10-26T13:00:00-04:00",
                "endTime": "2021-10-26T14:00:00-04:00",
                "isDaytime": true,
                "temperature": 58,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "17 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Light Rain",
                "detailedForecast": ""
            },
            {
                "number": 24,
                "name": "",
                "startTime": "2021-10-26T14:00:00-04:00",
                "endTime": "2021-10-26T15:00:00-04:00",
                "isDaytime": true,
                "temperature": 58,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "18 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Heavy Rain",
                "detailedForecast": ""
            },
            {
                "number": 25,
                "name": "",
                "startTime": "2021-10-26T15:00:00-04:00",
                "endTime": "2021-10-26T16:00:00-04:00",
                "isDaytime": true,
                "temperature": 58,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "21 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Heavy Rain",
                "detailedForecast": ""
            },
            {
                "number": 26,
                "name": "",
                "startTime": "2021-10-26T16:00:00-04:00",
                "endTime": "2021-10-26T17:00:00-04:00",
                "isDaytime": true,
                "temperature": 58,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "22 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Heavy Rain",
                "detailedForecast": ""
            },
            {
                "number": 27,
                "name": "",
                "startTime": "2021-10-26T17:00:00-04:00",
                "endTime": "2021-10-26T18:00:00-04:00",
                "isDaytime": true,
                "temperature": 58,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "23 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Heavy Rain",
                "detailedForecast": ""
            },
            {
                "number": 28,
                "name": "",
                "startTime": "2021-10-26T18:00:00-04:00",
                "endTime": "2021-10-26T19:00:00-04:00",
                "isDaytime": false,
                "temperature": 58,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "24 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/night/rain?size=small",
                "shortForecast": "Heavy Rain",
                "detailedForecast": ""
            },
            {
                "number": 29,
                "name": "",
                "startTime": "2021-10-26T19:00:00-04:00",
                "endTime": "2021-10-26T20:00:00-04:00",
                "isDaytime": false,
                "temperature": 58,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "25 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/night/rain?size=small",
                "shortForecast": "Heavy Rain",
                "detailedForecast": ""
            },
            {
                "number": 30,
                "name": "",
                "startTime": "2021-10-26T20:00:00-04:00",
                "endTime": "2021-10-26T21:00:00-04:00",
                "isDaytime": false,
                "temperature": 58,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "26 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/rain?size=small",
                "shortForecast": "Rain",
                "detailedForecast": ""
            },
            {
                "number": 31,
                "name": "",
                "startTime": "2021-10-26T21:00:00-04:00",
                "endTime": "2021-10-26T22:00:00-04:00",
                "isDaytime": false,
                "temperature": 57,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "26 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/rain?size=small",
                "shortForecast": "Rain",
                "detailedForecast": ""
            },
            {
                "number": 32,
                "name": "",
                "startTime": "2021-10-26T22:00:00-04:00",
                "endTime": "2021-10-26T23:00:00-04:00",
                "isDaytime": false,
                "temperature": 55,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "26 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/rain?size=small",
                "shortForecast": "Rain",
                "detailedForecast": ""
            },
            {
                "number": 33,
                "name": "",
                "startTime": "2021-10-26T23:00:00-04:00",
                "endTime": "2021-10-27T00:00:00-04:00",
                "isDaytime": false,
                "temperature": 54,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "28 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/rain?size=small",
                "shortForecast": "Rain",
                "detailedForecast": ""
            },
            {
                "number": 34,
                "name": "",
                "startTime": "2021-10-27T00:00:00-04:00",
                "endTime": "2021-10-27T01:00:00-04:00",
                "isDaytime": false,
                "temperature": 54,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "29 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/rain?size=small",
                "shortForecast": "Rain",
                "detailedForecast": ""
            },
            {
                "number": 35,
                "name": "",
                "startTime": "2021-10-27T01:00:00-04:00",
                "endTime": "2021-10-27T02:00:00-04:00",
                "isDaytime": false,
                "temperature": 53,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "29 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/rain?size=small",
                "shortForecast": "Rain",
                "detailedForecast": ""
            },
            {
                "number": 36,
                "name": "",
                "startTime": "2021-10-27T02:00:00-04:00",
                "endTime": "2021-10-27T03:00:00-04:00",
                "isDaytime": false,
                "temperature": 53,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "29 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/rain?size=small",
                "shortForecast": "Light Rain",
                "detailedForecast": ""
            },
            {
                "number": 37,
                "name": "",
                "startTime": "2021-10-27T03:00:00-04:00",
                "endTime": "2021-10-27T04:00:00-04:00",
                "isDaytime": false,
                "temperature": 52,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "28 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/rain?size=small",
                "shortForecast": "Light Rain",
                "detailedForecast": ""
            },
            {
                "number": 38,
                "name": "",
                "startTime": "2021-10-27T04:00:00-04:00",
                "endTime": "2021-10-27T05:00:00-04:00",
                "isDaytime": false,
                "temperature": 52,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "26 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/rain?size=small",
                "shortForecast": "Light Rain",
                "detailedForecast": ""
            },
            {
                "number": 39,
                "name": "",
                "startTime": "2021-10-27T05:00:00-04:00",
                "endTime": "2021-10-27T06:00:00-04:00",
                "isDaytime": false,
                "temperature": 51,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "25 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/rain?size=small",
                "shortForecast": "Light Rain",
                "detailedForecast": ""
            },
            {
                "number": 40,
                "name": "",
                "startTime": "2021-10-27T06:00:00-04:00",
                "endTime": "2021-10-27T07:00:00-04:00",
                "isDaytime": true,
                "temperature": 50,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "25 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Light Rain Likely",
                "detailedForecast": ""
            },
            {
                "number": 41,
                "name": "",
                "startTime": "2021-10-27T07:00:00-04:00",
                "endTime": "2021-10-27T08:00:00-04:00",
                "isDaytime": true,
                "temperature": 49,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "24 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Light Rain Likely",
                "detailedForecast": ""
            },
            {
                "number": 42,
                "name": "",
                "startTime": "2021-10-27T08:00:00-04:00",
                "endTime": "2021-10-27T09:00:00-04:00",
                "isDaytime": true,
                "temperature": 50,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "23 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Light Rain Likely",
                "detailedForecast": ""
            },
            {
                "number": 43,
                "name": "",
                "startTime": "2021-10-27T09:00:00-04:00",
                "endTime": "2021-10-27T10:00:00-04:00",
                "isDaytime": true,
                "temperature": 50,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "24 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Light Rain Likely",
                "detailedForecast": ""
            },
            {
                "number": 44,
                "name": "",
                "startTime": "2021-10-27T10:00:00-04:00",
                "endTime": "2021-10-27T11:00:00-04:00",
                "isDaytime": true,
                "temperature": 51,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "24 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Light Rain Likely",
                "detailedForecast": ""
            },
            {
                "number": 45,
                "name": "",
                "startTime": "2021-10-27T11:00:00-04:00",
                "endTime": "2021-10-27T12:00:00-04:00",
                "isDaytime": true,
                "temperature": 51,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "25 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Light Rain Likely",
                "detailedForecast": ""
            },
            {
                "number": 46,
                "name": "",
                "startTime": "2021-10-27T12:00:00-04:00",
                "endTime": "2021-10-27T13:00:00-04:00",
                "isDaytime": true,
                "temperature": 51,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "25 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Light Rain Likely",
                "detailedForecast": ""
            },
            {
                "number": 47,
                "name": "",
                "startTime": "2021-10-27T13:00:00-04:00",
                "endTime": "2021-10-27T14:00:00-04:00",
                "isDaytime": true,
                "temperature": 51,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "24 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Light Rain Likely",
                "detailedForecast": ""
            },
            {
                "number": 48,
                "name": "",
                "startTime": "2021-10-27T14:00:00-04:00",
                "endTime": "2021-10-27T15:00:00-04:00",
                "isDaytime": true,
                "temperature": 51,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "24 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Light Rain Likely",
                "detailedForecast": ""
            },
            {
                "number": 49,
                "name": "",
                "startTime": "2021-10-27T15:00:00-04:00",
                "endTime": "2021-10-27T16:00:00-04:00",
                "isDaytime": true,
                "temperature": 51,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "24 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Chance Light Rain",
                "detailedForecast": ""
            },
            {
                "number": 50,
                "name": "",
                "startTime": "2021-10-27T16:00:00-04:00",
                "endTime": "2021-10-27T17:00:00-04:00",
                "isDaytime": true,
                "temperature": 52,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "23 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Chance Light Rain",
                "detailedForecast": ""
            },
            {
                "number": 51,
                "name": "",
                "startTime": "2021-10-27T17:00:00-04:00",
                "endTime": "2021-10-27T18:00:00-04:00",
                "isDaytime": true,
                "temperature": 52,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "23 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Chance Light Rain",
                "detailedForecast": ""
            }
        ]
    }
}
"""
}
